[build]
  command = "npm run build"
  publish = "public" 
[[plugins]]
  package = "@netlify/plugin-inline-functions"
  [plugins.inputs]


[[plugins]]
  package = "@netlify/plugin-cache"
  [plugins.inputs]
